owner: feirm # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: "🌐 Web Client"
    url: https://feirm.com
  - name: "🔗 Platform API"
    url: https://api.feirm.com
    expectedStatusCodes:
      - 200
      - 404

status-website:
  cname: status.feirm.com
  favicon: https://feirm.com/favicon.ico
  logoUrl: https://feirm.com/favicon.ico
  name: Feirm Status
  introTitle: "**Privacy for everyone.**"
  introMessage: The Feirm Platform infrastructure is continuously monitored. If there are any disruptions in service, an update will be posted here.

