owner: feirm # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  cname: status.feirm.com
  logoUrl: https://feirm.com/favicon.ico
  name: Feirm Status
  introTitle: "**Privacy for everyone.**"
  introMessage: The Feirm Platform infrastructure is continuously monitored. If there are any disruptions in service, an update will be posted here.

